version: 2

macros:
  - name: get_cancellation_reason
    description: >
      Translates a flight's cancellation code into a human-readable reason. 
      The cancellation codes and their corresponding reasons are:
        - 'A': Carrier
        - 'B': Weather
        - 'C': National Air System (NAS)
        - 'D': Security
    arguments:
      - name: CancellationCode
        type: string
        description: "The cancellation code to be translated."
